version: "3.7"
services:
  react:
    container_name: myscope-frontend
    build: .
    restart: always
    ports:
      - "4173:4173"
    networks:
      - network1
networks:
    network1:
      name: examgen
      external: true