version: '3'
services: 
  mongodb:
    image:  mongo:4.4.17-focal
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=targonca
      - MONGO_INITDB_ROOT_PASSWORD=Szeretematejetigenesakakaotis
    networks:
      - network1
    restart: always
    volumes:
      - ./mongodb-data:/data/db


  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    networks:
      - network1
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=targonca
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Szeretematejetigenesakakaotis
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=csipesz
networks:
    network1:
      name: examgen
      external: true