version: '3'
services:
  api:
    build: .
    container_name: axe-api
    command: python3 ./src/api.py
    ports:
      - "7000:7000"
    networks:
      - network1
    restart: always
    volumes:
      - /srv/examgen/backend/volume:/src/src/data
networks:
  network1:
    external: true
    name: examgen


