version: '3'
services:
  myscope-api:
    build: .
    container_name: myscope-api
    command: python3 ./src/api.py
    ports:
      - "7000:7000"
    networks:
      - network1
    restart: always
    volumes:
      - /srv/Webtech/python/volume:/src/src/data
networks:
  network1:
    external: true
    name: examgen


